// Generated by CoffeeScript 1.6.3
(function() {
  var app, clientName, connect, fs, io, store;

  store = require('./store');

  connect = require("connect");

  clientName = '';

  app = connect().use(connect.logger()).use(connect["static"](__dirname + "/")).listen(8081);

  io = require('socket.io').listen(app);

  fs = require('fs');

  io.sockets.on('connection', function(socket) {
    var clientIp;
    clientName = JSON.stringify(socket[1]);
    clientIp = socket.handshake.address;
    return socket.on('client', function(data) {
      store({
        ip: clientIp.address + ':' + clientIp.port,
        userName: data['userName'],
        chat: data['chat'].toString()
      });
      socket.emit('server', {
        ip: clientIp.address + ':' + clientIp.port,
        userName: data['userName'],
        chat: data['chat']
      });
      return socket.broadcast.emit('broadcast', {
        ip: clientIp.address + ':' + clientIp.port,
        userName: data['userName'],
        chat: data['chat']
      });
    });
  });

}).call(this);
