// Generated by CoffeeScript 1.6.3
(function() {
  var Chat, db, exports, mongoose, schema;

  mongoose = require('mongoose');

  mongoose.connect('localhost', 'daemon');

  db = mongoose.connection;

  db.on('error', console.error.bind(console, 'connection error:'));

  db.once('open', function() {
    return console.log("yeap");
  });

  schema = mongoose.Schema({
    ip: 'string',
    userName: 'string',
    chat: 'string'
  });

  Chat = mongoose.model('Chat', schema);

  exports = module.exports = function(jsonObj) {
    var chat;
    chat = new Chat(jsonObj);
    return chat.save(function(err) {
      if (err) {
        return console.log(err);
      } else {
        return console.log('------store KO');
      }
    });
  };

}).call(this);
